### PR TITLE
gopherjs: allow using gopherjs outside of docker

### PR DESCRIPTION
**Pull request by thisconnect**
Current compile step only works in docker as the path expect to be
inside docker container. Allow usign make copile without docker.

### CODE REVIEW

**Comment by thisconnect** [comment]
@x1ddos I forgot how you added gopherjs to the path, maybe like this `ENV PATH="/gopherjs/:${PATH}"` ?

**Comment by x1ddos** [comment]
> @x1ddos I forgot how you added gopherjs to the path, maybe like this `ENV PATH="/gopherjs/:${PATH}"` ?

precisely. that should go into the [dockerfile](https://github.com/digitalbitbox/bitbox02-api-js/blob/26c50950/Dockerfile). i would insert it before the last line `CMD ["bash"]`.

**Comment by thisconnect** [comment]
added before the last line CMD ["bash"].

**Review by x1ddos — APPROVED** [review]
seems to work:

```
$ make dockerinit
docker build --no-cache --pull --force-rm -t bitbox02-api-js .
STEP 1/6: FROM golang:1.16-buster
Trying to pull docker.io/library/golang:1.16-buster...
...

$ make dockercompile
docker run -v `pwd`:/bitbox02-api-js --workdir=/bitbox02-api-js --rm -it bitbox02-api-js make compile
cd gowrapper && gopherjs build -o ../src/bitbox02-api-go.js

$ ls -l src/bitbox02-api-go.js
-rw-r--r-- 1 6783770 Nov  8 15:59 src/bitbox02-api-go.js
```

LGTM

**Pull request merged**
