### PR TITLE
docs: move method docs to separate file

### PR DESCRIPTION
**Pull request by Stadicus**
To simplifiy the README and avoid inconsistencies in the future, the methods documentation is moved to a seperate file. Existing documentation is removed from README and source code.

Minor wording adjustments for better readability.

### CODE REVIEW

**Comment by NickeZ** [comment]
The code should be documented. I don't think it is a good idea to have references to a markdown file.

**Comment by Stadicus** [comment]
I'm open to anything. This was discussed with @Tomasvrba with the goal to not have duplicate documentation in source code and the README. 

Going forward: 
* use duplicate documentation, both in methods.md and source code
* only use source code inline documentation (don't like)

What would you propose?

**Comment by NickeZ** [comment]
There should be enough documentation in the code so that you can use it without referencing other material. It should at least not contain links to github, in that case try to link within the repository.

As far as I can see the new file `methods.md` could be generated from the source code documentation. Here is one such tool for example: https://github.com/jsdoc/jsdoc

**Comment by Stadicus** [comment]
Thanks, I'll have a look. In terms of "Getting stuff done" I propose we use the duplicate documentation for now, and optimize documentation creation in the next iteration.

**Pull request merged**
